project:
  type: website

website:
  title: "Winfried Pohlmeier"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd
      - pubs.qmd
      - working_papers.qmd
      - teaching.qmd
      - downloads.qmd
    right:
      - icon: github
        href: https://w-pohlmeier.github.io/WP-Website/
        aria-label: GitHub
      - icon: envelope
        text: Email
        href: "mailto:mail.marvinschmitt@gmail.com" 

format:
  html:
    theme: default
    css: styles.css
    toc: true
    toc-depth: 4
  
editor: visual

