project:
  type: website

website:
  title: "Winfried Pohlmeier"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd
      - pubs.qmd
      - working_papers.qmd
      - teaching.qmd
      
format:
  html:
    theme: default
    css: styles.css
    toc: true
    toc-depth: 4

editor: visual

