project:
  type: website

website:
  title: "Anette Pohlmeier"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: Lebenslauf
      - href: teaching.qmd
        text: Lehre
      - href: blog.qmd
        text: Blog
    right:
      - icon: envelope
        href: mailto:Anette.pohlmeier@t-online.de

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

# https://bootswatch.com/ 