project:
  type: website

website:
  title: "Winfried Pohlmeier Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd
      - pubs.qmd
      
format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual

