---
title: "Bunt statt Blau bei der Fasnacht"
author: "Anette Pohlmeier"
date: 2026-2-01
categories: [Alkohol]
---

Im Chemieunterricht habe ich gelernt: „Jeder Alkohol ist giftig, C~2~H~5~OH ist am wenigsten giftig.“ Fasnacht und Alkohol sind eng verknüpft. Alkohol hebt die Stimmung, wirkt anregend, entspannend und angstlösend. Doch er ist ein Zellgift, das unter anderem Gehirn, Leber und Herz schädigt und auch die psychische Gesundheit beeinträchtigen kann. Alkohol wird über die Schleimhaut des Verdauungstraktes ins Blut aufgenommen und verteilt sich dann im gesamten Körper, v.a. im Gehirn. Menschen, die wenig Alkohol trinken, merken bereits geringe Mengen, durch Wahrnehmungs-, Konzentrations-, Koordinations- und Gleichgewichtsstörungen. Schwere Trinker wirken selbst bei 3 Promille, diese Menge gilt als lebensbedrohlich, noch relativ vernünftig. Die höchste Menge, die ich bei Gewahrsamkeitsuntersuchungen bei der Polizei in Radolfzell gemessen habe, war 5,4 Promille. Doch den Weltrekord hält immer noch ein 45-jähriger Pole aus dem Dorf Skierniewice – mit 12,3 Promille im Jahr 2004. Nach einem Saufgelage wurde er auf dem Heimweg von einem Auto überfahren  - und hat beides überlebt. Werte über 4 Promille sind oft tödlich, es kommt zur Lähmung des Atemzentrums, Koma und Kreislaufversagen. 
Durch Alkoholkonsum steigt die Unfallgefahr: Risiken und Hindernisse werden unterschätzt oder zu spät erkannt, die eigenen Fähigkeiten werden überschätzt. Zusätzlich tragen eine gestörte Wahrnehmung und Reaktionsfähigkeit sowie Gangstörungen zu einem erhöhten Unfallrisiko bei.
Neben akuten Wirkungen spielen die langfristigen Wirkungen des chronischen Alkoholkonsums für die Gesundheit die bedeutendere Rolle. Mit der Sucht kommt es zu Persönlichkeitsveränderungen, psychische Erkrankungen (wie Angststörungen),  Herzerkrankungen, Schlaganfall und Demenz nehmen zu. Neben Leberschäden  kommt es auch zur Zunahme von verschiedenen Krebserkrankungen wie Tumore der Mundhöhle, des Rachens, der Speiseröhre, des Darms und der Leber und v.a. bei Frauen zu Brustkrebs. Frauen vertragen weniger Alkohol als Männer. Der Anteil an Körperflüssigkeit, auf die sich Alkohol verteilen kann, ist bei Frauen geringer und Alkohol kann schlechter verstoffwechselt werden. (das Enzym Alkoholdehydrogenase wird weniger produziert) 
Einen risikofreien Alkoholkonsum gibt es weder für Frauen noch für Männer. Der Grenzwert für einen risikoarmen Alkoholkonsum liegt für gesunde erwachsene Frauen bei einem kleinen Glas Bier oder Wein täglich – bei Männern darf es die doppelte Menge sein. An mindestens zwei Tagen pro Woche sollten Männer wie Frauen ganz auf Alkohol verzichten. Damit sinkt das Risiko für eine schleichende Abhängigkeit.
Es kann schwer sein, an der Fasnacht ganz auf Alkohol zu verzichten. Da Nahrung den Alkoholtransport ins Blut verzögert, sollten sie immer gut gesättigt sein. Trinken Sie nur kleine Schlucke, stellen Sie das Glas zwischendurch ab und trinken Sie ein Glas Wasser, um den Flüssigkeitsverlust auszugleichen und den Konsum zu verlangsamen. Lassen sie sich von niemandem zum Trinken animieren, sagen Sie „Nein“. Vermeiden Sie Partys mit Flatrates oder Trinkspielen, wo Sie leicht zu viel trinken könnten.
Mit diesen Tipps und viel guter Laune wird Fasnacht mit weniger Alkohol wieder zum Erlebnis. Mit hat Praxisbefreiung immer Spaß gemacht. Narri-Narro!
