---
title: "Cannabis"
author: "Anette Pohlmeier"
date: 2025-06-01
categories: [Drogen, Medikamente]
---

Cannabis sativa gehört zu den ältesten Kulturpflanzen der Menschheit. Sie stammt vermutlich aus Zentralasien oder Ägypten. Bereits 8000 v. Chr. waren aus Hanf gefertigte Taue im Gebrauch. Um 2700 v. Chr. wurde die medizinische Verwendung von Cannabisbestandteilen in China dokumentiert. Die unterschiedlichen Cannabispflanzen: C. sativa, C. ruderalis und C. indica haben eine Höhe von bis zu 5 m, andere sind kleiner und eignen sich eher zum Eigenanbau. Die Pflanzen weisen bis zu 600 unterschiedliche Substanzen auf, in unterschiedlichen Dosierungen, die auch vom Standort und der Pflückzeit abhängig sind. Die Hauptbestandteile sind Cannabinoide (113, darunter das THC und das CBD) und Terpene (120), daneben gibt es Stickstoffverbindungen, Aminosäuren, Proteine und Enzyme, Zucker, Phenole und einige andere chemische Verbindungen, die in unterschiedlicher Weise antientzündlich, auf den Magen-Trakt und auf das Gehirn wirken. Auf Grund dieser vielen unterschiedlichen Bestandteile kann die Wirkung von Cannabis nicht sicher bewertet werdenund entspricht nicht den sonst üblichen hohen Sicherheitsstandards, die für eine Medikamentenzulassung gefordert werden. Begriffsbestimmung: Marihuana = Grass wird aus den getrocknete Blüten- und Blattstände hergestellt, Haschisch besteht aus dem gepressten Harz und ist stärker wirksam als „Grass“. Am konzentriertesten ist Haschisch-Öl, es hat den höchsten THC-Gehalt (Delta-9-Tetrahydrocannibinol). THC ist das bekannteste und am reichlichsten vorhandene Cannabinoid in Cannabis. Es ist für die psychoaktive Wirkung verantwortlich, indem es Teile des Gehirns stimuliert und die Freisetzung von Dopamin bewirkt. Dadurch kommt es zu einem Gefühl der Euphorie, des Wohlbefindens und der Entspannung, Menschen neigen zu Jubeln und Lachen. THC verstärkt die Wahrnehmung sensorischer Stimuli und des eigenen Körpers. Es entsteht ein Gefühl der Körper schwebe oder sinke. Kognitiv kommt es zu einer Störung der Zeitwahrnehmung, zu Gedächtnislücken und Konzentrationsschwierigkeiten, vor allem wenn der Konsum in der Jugend beginnt. Obwohl viele Nebenwirkungen wie Psychosen, Schwindel, Übelkeit, Müdigkeit, Schlafstörungen, Verwirrtheit / Angst, Gewichtzunahme, und viele mehr, beschrieben sind, sterben mehr Menschen durch Alkoholkonsum als durch Cannabis. Für Spastik bei Multipler Sklerose und bei Chemotherapie bedingten Erbrechen sind cannabishaltige Medikamente schon seit Längerem lange zugelassen. Ab März 2017 besteht für alle Ärzt*innen nach Genehmigung durch den medizinischen Dienst der Krankenkassen, die Möglichkeit Patienten mit einer schwerwiegenden Erkrankung, Cannabis auf Kassenrezept zu verordnen. Insbesondere bei der Behandlung chronischer (Nerven-) Schmerzen und anderer schwerwiegender Symptome. Allerdings ist die Studienlage für viele Erkrankungen uneinheitlich und dadurch erschwert, dann nicht einzelne Cannabinoide getestet werden, sondern die Pflanze mit all ihren Wirkstoffen. Deshalb sind Neurologen und Schmerztherapeuten durchgehend sehr skeptisch bei der Verordnung, zumal häufig Suchtpatienten durch simulierte Schmerzen an die kostenlose Verordnung „ihres Stoffes“ kommen wollen. Eine umfassende und individuelle Beratung durch medizinisches Fachpersonal ist essenziell, um die bestmöglichen Therapieformen zu finden und die Sicherheit der Patient*innen zu gewährleisten. Cannabis kann einen therapeutischen Effekt haben, es ist aber sicherlich keine harmlose Wunderdroge.
