---
title: "Der Mai ist gekommen, die Bäume schlagen aus"
author: "Anette Pohlmeier"
date: 2025-05-01
categories: [Immunologie]
---

# „Der Mai ist gekommen, die Bäume schlagen aus“

Nicht für alle Menschen ist das ein Grund zur Freude, etwa 12 Millionen Menschen leiden in Deutschland an Heuschnupfen (14,8 Prozent). Verantwortlich dafür sind „Frühblüher“ wie Birke, Hasel, Gräser und Kräuter. Besonders gefährlich sind die Pollen der aus Nordamerika stammende Pflanze Ambrosia, sie haben ein fünffach höheres Allergie Risko Pollen als andere Gräser. 
Meist beginnt der Heuschnupfen vor dem 25. Lebensjahr, auch schon bei Kindern. Die Ursache von Heuschnupfen liegt in unserem Immunsystems, das dem Schutz des Körpers vor ihm fremden und potenziell gefährlichen Stoffen dient. Erkennt das Immunsystem solche körperfremden Stoffe (sogenannte Antigene, wie z.B. Bakterien, Viren, Pilze, aber auch Tumorzellen), werden zu deren Abwehr spezifische Antikörper (Immunglobuline) produziert. Bei Allergie-bedingten Überempfindlichkeitsreaktionen des Immunsystems werden IgE-Antikörper gegen vermeintlich gefährliche Stoffe z.B. aus Pollen, Nahrungsmittel etc., gebildet. Schon beim nächsten Kontakt erinnert sich das Immunsystem und erkennt diesen Stoff wieder. Um die „Eindringlinge“ abzuwehren, werden große Mengen von Histamin und andere Gewebshormone freigesetzt, die dazu führen, dass Drüsen zur Abgabe von Sekret stimuliert werden, Nerven werden gereizt und verursachen dadurch Juck- und Niesreiz, sie bewirken auch eine Gefäßerweiterung, die zur Rötung und Schwellung der Schleimhäute führt. Betroffen sind v.a. die Nase, die Augen und der Mund, es kommt es zu wässrigem Schupfen, tränenden Augen mit Bindehautrötung und verstopfter Nase. Ist die Lunge betroffen sind die Symptome deutlich ernster. Es kommt zu Husten, v.a. nachts mit Atemnot und Asthma und bei Kindern häufig zu dem gefürchteten Pseudokrupp, der nicht selten einer notärztliche Versorgung bedarf. 
Die Disposition zum Heuschnupfen ist oft vererbt. Wenn kein Familienmitglied Allergiker ist, haben Kinder ein Allergierisiko von etwa 5 bis 15 Prozent. Wenn ein Elternteil Allergiker ist, beträgt das Risiko etwa 20 bis 40 Prozent und steigert sich auf 40-80 Prozent, wenn beide Eltern allergisch sind. Die sogenannte Hygienehypothese geht davon aus, dass die Körperabwehr bei sehr ausgeprägter Hygiene in der Kindheit unterfordert ist und deswegen irgendwann auch gegen harmlose Substanzen vorgeht. Kinder, die in ländlicher Umgebung (zum Beispiel auf dem Bauernhof) aufwachsen, weisen ein niedrigeres Allergierisiko auf. Stoffe in der Umgebungsluft, welche die Atemwege reizen (Feinstaub, Zigarettenrauch, Autoabgase etc.), können zur Entstehung einer Allergie (Heuschnupfen etc.) und Asthma beitragen. 
Therapeutisch stehen v.a. Antihistaminika, die die Andockstellen des Histamins im Körper reduzieren und bei schweren Fällen auch Kortison zur Verfügung. Die Substanzen wirken relativ schnell (Tabletten innerhalb von einer Stunde, Nasensprays innerhalb von 15 Minuten) und können deshalb bei akuten Beschwerden eingesetzt werden. Eine ursächliche Behandlungsform des Heuschnupfens ist die spezifische Immuntherapie mit Allergenen. Sie soll das Immunsystem über einen längeren Zeitraum hinweg an die allergieauslösenden Pollen gewöhnen. Einige Ärzte setzen Homöopathie oder Akupunktur ein, um Heuschnupfen-Beschwerden zu lindern. Allerdings ergibt sich kein klares Bild hinsichtlich der Wirksamkeit. Bis heute gibt es zu wenig aussagekräftige Studien. Mit den medizinischen Therapiemöglichkeiten gelingt es meist, dass jeder im Mai „singet und jauchzet das Herz zum Himmelszelt: wie bist du doch so schön, du weite, weite Welt!“ (Liedtext: Emanuel Geibel)
