---
title: "Fasten"
author: "Anette Pohlmeier"
date: 2025-06-01
categories: [Diät]
---

„Am Aschermittwoch ist alles vorbei“ 
Wie im Karnevalslied aus dem Jahr 1953 beginnt am Aschermittwoch im Christentum das traditionelle Fasten bis in die Osternacht am 19. April. Juden fasten am Versöhnungstag (Jom Kippur) und in der islamischen Kultur gibt es den jährliche Fastenmonat Ramadan. Fast drei Viertel der Bevölkerung halten Fasten für sinnvoll. Die größte Zustimmung zum Thema Fasten gibt es mit 84 Prozent in der Altersklasse der 18- bis 29-Jährigen.
Fasten ist vielfältig und beinhaltet den Verzicht auf sozial Media (27%), auf Süßes (70 %) und Fleisch (52 %), der freiwillige Verzicht auf Alkohol (75%) oder der völlige Nahrungsverzicht. Unterformen sind Heilfasten mit Molke oder sog. Formula-Diäten (Modifast oder SlimFast) oder Intervallfasten (z.B. im Rhythmus 16:8). Aufgrund der großen Energiereserven von gesunden Menschen und der Stoffwechselanpassung des Organismus kann ein normalgewichtiger Mensch 50 bis 70 Tage ohne Nahrungszufuhr überleben. Ein 27-jähriger Mann ist Rekordinhaber der wahrscheinlich längsten, gut dokumentierten Fastenperiode mit einem initialen Körpergewicht von 207 Kilogramm, der über eine Zeitdauer von 382 Tagen ununterbrochenen Fastens 60% seines Körpergewichts verlor.
Dem Körper werden bei einer Fastenkur nicht nur die energieliefernden Nährstoffe Kohlenhydrate, Eiweisse und Fette vorenthalten, sondern auch lebensnotwendige Vitamine und Mineralstoffe. Neben dem Wunsch nach Gewichtsreduktion stehen heute zunehmend gesundheitsfördernden Effekte des Fastens im Vordergrund, die v.a. beim Langzeitfasten festgestellt werden konnten. Dazu gehören Stressresistenz, Steigerung der Immunabwehr, Blutdrucksenkung, verbesserte Blutzuckereinstellung und eine Verbesserung des Schlafs und der Stimmung. Außerdem werden kognitive Leistungssteigerung beschrieben und zumindest bei Mäusen die Förderung der Langlebigkeit. Schon der alleinige Verzicht auf Alkohol bewirkt eine Verbesserung des Leberstoffwechsels, eine Entlastung des Magen-Darm-Kanals und der Bauchspeicheldrüse sowie eine Steigerung der Ausdauer und der Aktivität. Die positiven Auswirkungen der Abstinenz auf den Schlaf bemerken viele Menschen schon in der ersten Woche. Fällt es schwer auf Alkohol zu verzichten, ist das ein Warnsignal und Anlass, seinen Konsum grundsätzlich zu überdenken. Die [„Kenn-dein-Limit-Kampagne“](https://www.kenn-dein-limit.de/) der Bundeszentrale für gesundheitliche Aufklärung (BzgA) unterstützt Promille-Abstinenzler mit einem speziellen Angebot. Neben Informationen zum Alkoholverzicht gibt es hier auch praktische Tipps zum Durchhalten.
Mein Fazit: Am Aschermittwoch ist nicht alles vorbei, sondern es kann auch ein Datum für einen Neuanfang und ein gesünderes Leben sein. 
