---
title: "Grippe Impfung"
author: "Anette Pohlmeier"
date: 2024-10-01
categories: [Immunologie]
---

Die Zielvorgaben der Europäischen Union für ältere Menschen für eine Grippe-Impfung beträgt
75 %, in Deutschland werden jedoch nur 43 % der Menschen über 60 Jahre geimpft. Die STIKO
empfiehlt die Impfung auch für Schwangere, medizinisches Personal (Ärzte sind zu 81% geimpft)
und jüngere Menschen mit Grunderkrankungen wie z.B. Lungenerkrankungen, Herz-Kreislauf-Erkrankungen
oder Diabetes. Da mit zunehmendem Alter die Leistungsfähigkeit des Immunsystems
abnimmt, steht für ältere Menschen ein Hochdosis-Impfstoff zur Verfügung.
Zusammen mit der Influenza-Impfung kann gegen Covid-19 (Corona) geimpft werden. Der vollständige Impfschutz ist nach ca. 10-14 Tagen aufgebaut, deshalb sollte die Impfung ab Oktober erfolgen.
Grippeviren verändern sich ständig, es gibt unterschiedliche Virusstämme (Typ A, Typ B und Typ
C, die wiederrum durch 18 unterschiedliche H- und 11 unterschiedliche N-Proteine differenziert
werden). Z.B. Vogelgrippe (A/H5N1), Spanische Grippe (A/H1N1), Hongkong-Grippe (A/H3N2). Der
saisonale Influenza-Impfstoff enthält Bestandteile jener Virus-Varianten, die am wahrscheinlichsten
in der kommenden Saison das Infektionsgeschehen dominieren werden. Die Impfung schließt
die Erkrankung nicht zu 100% aus. Es kann sein, dass der Impfstoff die vorherrschende Virusvariante
nicht voll abdeckt, oder die Infektion kurz vor der Impfung stattgefunden hat. Fieberhafte,
sgn. Grippale Infekte können auch durch andere Erreger verursacht sein, es handelt sich dann aber
nicht um ein Versagen der Influenza-Impfung.
Es gibt zunehmend Hinweise darauf, dass die Influenza auch ein Risikofaktor für Herzinfarkte bzw.
Schlaganfälle ist, die Influenza-Impfung kann davor schützen.
Der Impfstoff ist in der Regel gut verträglich. Nach der Impfung mit dem Influenza-Totimpfstoff
kann es – wie bei anderen Impfungen auch – vorübergehend zu Lokalreaktionen (leichte Schmerzen,
Rötung und Schwellung an der Impfstelle) kommen (sog. Impfreaktionen). Diese sind Folge der
erwünschten, natürlichen Auseinandersetzung des Immunsystems mit dem Impfstoff.
Wie jede Impfung kann v.a. die Grippe-Impfung bei älteren Menschen Leben retten. Deshalb
die Empfehlung: <span style="color: red; font-size: 20px;">Lassen Sie sich impfen.</span>