---
title: "Herbstzeit ist Grippezeit"
author: "Anette Pohlmeier"
date: 2025-10-01
categories: [Grippe,Impfung]
---

Die Blätter der Bäume und die Temperaturen fallen, warme Jacke werden wieder hervor geholt und mit ihnen auch die Taschentücher. Für viele heißt das: erhöhte Anfälligkeit, verschnupfte Nasen und mühsames Husten. Die Grippewelle rollt los, oder ist es doch nur eine harmlose Erkältung? 
Die echte Grippe, auch Influenza genannt, ist eine ernsthafte, mitunter auch lebensbedrohliche Krankheit v.a. der Atemwege, die durch Influenzaviren der Gattung A, B oder C ausgelöst wird. Influenzaviren verändern sich ständig und bilden häufig neue Varianten. Durch diese Änderungen kann man sich im Laufe seines Lebens öfter mit Grippe anstecken und erkranken. Deshalb wird der Influenza-Impfstoff nahezu jedes Jahr neu angepasst. 
Die Virusgrippe ist sehr ansteckend. Beim Niesen, Husten oder Sprechen gelangen kleinste, virushaltige Tröpfchen von Erkrankten in die Luft und können von anderen Menschen in der Nähe eingeatmet werden. 
Nach ca. 1 bis 4 Tagen beginnen die ersten Beschwerden, meist mit einem plötzlich einsetzenden Krankheitsgefühl, Fieber tritt häufig bis 39° auf, Halsschmerzen und trockener Husten, begleitet von Muskel-, Glieder-, Rücken- oder Kopfschmerzen. Die häufigste Komplikation bei einer Grippe ist die Lungenentzündung, die auch tödlich v.a. Vorerkrankten und Menschen über 65 Jahre enden kann. Gefährdet sind auch Übergewichtige und Schwangere. 
In Erinnerung bleibt die Spanische Grippe, die ab 1918 ausbrach, sie kostete wahrscheinlich mindestens 20 bis 50 Millionen Menschenleben, die Asiatische Grippe (1957, 1-2 Millionen Tote) und die Hongkong-Grippe (1968, 1 Million Tote). Zum Vergleich dazu kam es zu 20 Millionen toten Menschen durch Covid, seit 2019.
In erster Linie besteht die Behandlung einer Grippe aus Bettruhe, reichlich trinken und Schonung. Fieber und Schmerzen können mit Paracetamol und nichtsteroidalen Antirheumatika (NSAR), wie Aspirin und Ibuprofen, behandelt werden. In Einzelfällen werden auch antivirale Medikamente eingesetzt. Nur wenn eine bakterielle Superinfektion vorliegt, werden auch Antibiotika eingesetzt. 
Da es über 200 unterschiedliche Viren gibt, die eine Erkältung verursachen können, kann gegen grippale Infekte nicht geimpft werden. Meist handelt es sich um Rhinoviren, sie sind die Hauptverantwortlichen für den typischen Erkältungsschnupfen, können aber auch Nasennebenhöhlenentzündungen und Bronchitis auslösen. Da sie sehr kälteresistent sind, haben sie in der kalten Jahreszeit optimale Voraussetzungen zur Verbreitung.
Durch Vorsichtsmaßnahmen, wie gründliches Hände waschen, in Grippewellen das Vermeiden von Händeschütteln, Abstand halten und Maske tragen, aber v.a. durch die jährlich stattfindende Impfung können wir getrost mit Mütze und Schaal den Wind und die bunten Blätter im Herbst genießen. 

Weitere Informationen finden Sie auf <https://infektionsschutz.de> , oder bei <https://influenza.rki.de/>.
