---
title: "Sommer und Sonnenschein"
author: "Anette Pohlmeier"
date: 2024-05-01
categories: [Umwelt]
---


Sommer und Sonnenschein - sobald die Sonne scheint, wollen wir ihre Wärme genießen. Im
Juni erwarten wir sogar mit 278 Sonnenstunden die höchste Sonnenbestrahlung im Jahr. Ohne
Sonne gibt es kein Leben auf der Erde. Die Sonnenstrahlung besteht zu ca. 50% aus sichtbarem
Licht, zu ca. 44 % aus Infrarot (Wärme-) Strahlung und zu ca. 6% aus UV-Strahlung.
Die meiste UV-Strahlung wird zwar in der Atmosphäre abgefangen v.a. das schädliche UVC wird
nahezu vollständig in der Ozonschicht absorbiert. Aber - wer sich den Sonnenstrahlen – und somit
der UVA und UVB-Strahlung aussetzt, riskiert akut einen Sonnenbrand. Langfristige Folgen
zu hoher Sonnenbestrahlung sind Binde- und Hornhautentzündungen und vorzeitige Hautalterung.
Zu den schwerwiegendsten Spätfolgen gehören insbesondere Hautkrebserkrankungen. In
Deutschland erkrankt jeder siebte Mann und jede neunte Frau bis zum Alter von 75 Jahren an
Hautkrebs – Tendenz steigend: Seit 2000 hat sich die Hautkrebsneuerkrankungsrate (Inzidenz)
in Deutschland mehr als verdoppelt.
Besonders gefährdet sind Kinder (insbesondere Babys) und Jugendliche, Menschen, mit empfindlicher,
heller Haut, die schnell einen Sonnenbrand entwickeln und nicht oder nur wenig
bräunen, Menschen mit vielen und/oder medizinisch auffälligen Pigmentmalen (Leberflecke,
Muttermale).
Die wichtigsten Sonnenregeln:
- Meiden Sie die Sonne, am besten nicht mehr als 30 Minuten täglich.
- Tragen Sie langärmelige Shirts oder Blusen, einen breitkrempigen Hut und Sonnenbrillen.
Im Handel ist spezielle Kleidung mit hohem Sonnenschutz erhältlich.
- Verwenden Sie Sonnenschutzcremes, v.a. auch nach dem Baden. Denken Sie auch an die
Ohren und den Hals. Achtung !! Nachcremen verlängert nicht die Schutzwirkung.
- Verzichten Sie in der Sonne auf Parfüms und Deos. So vermeiden Sie unschöne Pigmentflecken.