---
title: "Uns ist ein Kind geboren"
author: "Anette Pohlmeier"
date: 2024-12-01
categories: [Gynäkologie]
---

2023 kamen in Deutschland 692 989 Kinder zur Welt. Bevor es soweit ist, vergehen faszinierende
9 Monate. Es fängt damit an, dass zirka 10 bis 14 Tage vor der nächsten zu erwartenden Regel eine
(manchmal auch mehrere) Eizelle aus dem Eierstock, dem Ovar der Frau, in den Eileiter abgegeben.
Nur ca.100 der vielen Millionen Samenzellen des Mannes finden den Weg zur Eizelle, nur eine
einzige schafft es, die Eihülle zu durchdringen. Danach verschmilzt das genetische Programm des
Vaters mit dem der Mutter und wird zu einem neuen Menschen. Ei und Samenzelle haben jeweils
nur 23 statt 46 Chromosomen, durch ihre Verbindung entsteht eine neue Zelle mit 46 Chromosomen,
jedes davon enthält tausende von Genen die Geschlecht, Augenfarbe, Gesichtszüge, Größe,
Temperament usw. bestimmen. Das im Eileiter befruchtete Ei wird in etwa 4 bis 6 Tagen zur Gebärmutter
transportiert und nistet sich in die Gebärmutterschleimhaut ein, ab dem 10. Tag ist der
Embryo an den mütterlichen Kreislauf angeschlossen. Kindliche und mütterliche Blutgefäße sind
nur durch wenige Zellschichten von einander getrennt, die Plazentaschranke schütz den Embryo,
ist allerdings durchlässig für Alkohol, Nikotin, leider aber auch Viren. Jeder Tropfen Alkohol kann
den Embryo schädigen, deshalb besteht in der Schwangerschaft striktes Alkohol- und Nikotinverbot.
Ab dem 22. Tag, also in der 5. SSW, beginnt das Herz zu schlagen, dann entwickelt sich das
Gehirn, die Ohren, Augen, Arme und Beine, zuletzt die Zähne, Gaumen und äußeres Genitale. Das
Gehirn entwickelt sich am Anfang des dritten Monats rasant, durchschnittlich werden während
einer Schwangerschaft pro Minute 250 000 Nervenzellen gebildet. Ab der 12. Schwangerschaftswoche
kann der Fötus Arme und Beine bewegen, die aber erst ab der 16. Schwangerschaftswoche
von der Mutter gespürt werden. Was für ein tolles Gefühl, neues Leben zu spüren. Nerven und
Muskeln arbeiten zusammen, der Magen bildet die ersten Verdauungssäfte, der Fötus, obwohl er
nur 5 Zentimeter groß und 20 Gramm schwer ist, trinkt Fruchtwasser und seine Nieren scheiden
Urin aus,
Während der Schwangerschaft verändert sich auch der Körper der Frau, in den ersten Monaten
kommt es häufig zu Übelkeit und Erbrechen. Das Blutvolumen, das das Herz jede Minute pumpt,
erhöht sich im Laufe der Schwangerschaft um 30 bis 50 %, dadurch müssen auch die Nieren mehr
arbeiten. Die Anzahl der weißen Blutkörperchen, die Infektionen bekämpfen, nimmt zu. Weitere
Veränderungen sind die gesteigerte Atmung und Hautveränderungen. Leider kommt es auch
häufig zu Rückenschmerzen durch Banddehnungen und natürlich kommt es zu einer Gewichtszunahme
von 10 bis 16 Kilogramm. Um die Gefahr von Missbildungen zu verringern, erhält die
Schwangere Vitamine, Folsäure, Jod und Omega 3 Fettsäuren.
Nach 280 Tagen oder 40 Wochen ist das Kind gut entwickelt und kann geboren werden. Aber nur
etwa 5% aller Kinder kommen am errechneten Geburtstermin zur Welt, 90% in den 2 Wochen
davor oder danach. Liegt das Kind richtig, werden zuerst Hinterhaupt, dann Stirn und Gesicht
geboren, es folgen die Schultern und dann der Rest des Körpers. Die meisten Kinder sind bei der
Geburt 48-54 Zentimeter groß und wiegen zwischen 3000 und 4000 Gramm. Unsere Aufgabe ist
es, sie mit Liebe und -Führsorge auf dieser Welt zu begrüßen und zu begleiten.
Ein herzlichen Willkommen an alle kleinen Erdenbürger
und Frohe Weihnachten.